Files ready for static Review
lukexjohnson/ITC205-Group-4 pull request #20
Opened 2018-08-15 11:59 UTC by Millsy66

Static Review of Paul's Files using  the  following Style Guide:

•	All class, variable, and method names should be meaningful. E.g. for a method that lists books, the name should be listBooks(), rather than lbk(). 
•	Class, variable, and method names should not use abbreviations, except for common acronyms (e.g. html rather than HyperText Markup Language) 
•	Class names should start with a capital and use CamelBack. 
•	Variable names should be nouns or noun phrases, start with a lower case letter and use camelBack. 
•	Method names should be verbs or verb phrases, start with a lower case letter and useCamelBack. 
•	Indentation increments should be 4 characters. 
•	All variables and operators MUST be separated by white space. E.g.: 
Not: 
a=b+c+d; 
Rather: 
a = b + c + d; 
•	Anywhere curly brackets MAY be used, they MUST be used. E.g.: 
Not: 
if (condition) 
some single line of optional code; 
further non optional code; 
Rather: 
if (condition) { 
some single line of optional code; 
} 

•	Random rules that must also be enforced: 
•	There should be no method calls within argument lists of any method calls. 
•	No calculations within Boolean expressions 
•	No negated Boolean variable names or negated Boolean methods. E.g. ‘isError’ rather than ‘isNoError’. 
•	Singletons should return their sole instance through a method called getInstance() 
•	All class and method declarations should be separated from the previous block of code by 2 space lines.

2018-08-15 13:20 UTC, bcurby requested changes
Please fix D1 - D61 for static review

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/FixBookControl.java
> +  //File ready for Static review
D1 - whole FixBookControl.java file - Change tabs -> 4 spaces

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/FixBookControl.java
> +  //File ready for Static review
D2 - line 24 FixBookControl.java - Change UIState -> UiState

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/FixBookControl.java
> +  //File ready for Static review
D3 - line 44 FixBookControl.java - remove method call from argument list of ui.display()

Replace with:

String currentBookInfo = currentBook.toString();
	   ui.display(currentBookInfo);

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/FixBookControl.java
> +  //File ready for Static review
D4 - line 45 FixBookControl.java - Change UIState -> UiState

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/FixBookControl.java
> +  //File ready for Static review
D5 - line 59 FixBookControl.java - Change UIState -> UiState

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/FixBookControl.java
> +  //File ready for Static review
D6 - line 69 FixBookControl.java - Change UIState -> UiState

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/FixBookControl.java
> +  //File ready for Static review
D7 - line 71 & 72 FixBookControl.java - Remove lines of whitespace between closing braces

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/FixBookUI.java
>  	public static enum UIState { INITIALISED, READY, FIXING, COMPLETED };
D8 - line 6 FixBookUI.java - Change UIState -> UiState

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/FixBookUI.java
>  	public static enum UIState { INITIALISED, READY, FIXING, COMPLETED };
D9 - line 10 FixBookUI.java - Change UIState -> UiState

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/FixBookUI.java
>  	public static enum UIState { INITIALISED, READY, FIXING, COMPLETED };
D10 - line 16 FixBookUI.java - Change UIState -> UiState

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/FixBookUI.java
>  	public static enum UIState { INITIALISED, READY, FIXING, COMPLETED };
D11 - line 21 FixBookUI.java - Change UIState -> UiState

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/FixBookUI.java
>  	public static enum UIState { INITIALISED, READY, FIXING, COMPLETED };
D12 - line 26 FixBookUI.java - Change method run -> runFixBook

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/FixBookUI.java
>  	public static enum UIState { INITIALISED, READY, FIXING, COMPLETED };
D13 - line 27 FixBookUI.java - Change method output -> displayOutputMessage

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/FixBookUI.java
>  	public static enum UIState { INITIALISED, READY, FIXING, COMPLETED };
D14 - line 34 FixBookUI.java - Change method input -> displayInputMessage

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/FixBookUI.java
>  	public static enum UIState { INITIALISED, READY, FIXING, COMPLETED };
D15 - line 37 & 38 FixBookUI.java - Move else up onto line with closing brace on line 37 and then delete line 38 whitespace e.g. 
} else {

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/FixBookUI.java
>  	public static enum UIState { INITIALISED, READY, FIXING, COMPLETED };
D61 - line 41 FixBookUI.java - Change e -> exception

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/FixBookUI.java
>  	public static enum UIState { INITIALISED, READY, FIXING, COMPLETED };
D16 - line 42 FixBookUI.java - Change method output -> displayOutputMessage

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/FixBookUI.java
>  	public static enum UIState { INITIALISED, READY, FIXING, COMPLETED };
D17 - line 48 FixBookUI.java - Change method input -> displayInputMessage

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/FixBookUI.java
>  	public static enum UIState { INITIALISED, READY, FIXING, COMPLETED };
D18 - line 59 FixBookUI.java - Change method output -> displayOutputMessage

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/FixBookUI.java
>  	public static enum UIState { INITIALISED, READY, FIXING, COMPLETED };
D19 - line 63 FixBookUI.java - Change method output -> displayOutputMessage

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/FixBookUI.java
>  	public static enum UIState { INITIALISED, READY, FIXING, COMPLETED };
D20 - line 70 FixBookUI.java - Change method input -> displayInputMessage

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/FixBookUI.java
>  	public static enum UIState { INITIALISED, READY, FIXING, COMPLETED };
D21 - line 76 FixBookUI.java - Change method output -> displayOutputMessage

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/FixBookUI.java
>  	public static enum UIState { INITIALISED, READY, FIXING, COMPLETED };
D22 - line 81 FixBookUI.java - Change method display -> displayMessage

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/Loan.java
D23 - line 11 Loan.java - Change loanID -> loanId

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/Loan.java
D24 - line 20 Loan.java - Change loanID -> loanId

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/Loan.java
D25 - line 41 Loan.java - Change method getId -> getLoanId

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/Loan.java
D26 - line 42 Loan.java - Change loanID -> loanId

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/Loan.java
D27 - line 55 Loan.java - Change loanID -> loanId

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/Loan.java
D28 - line 58 Loan.java - Change (book.id()) -> (book.getBookId())

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/Loan.java
D29 - line 79 Loan.java - Remove line of whitespace between closing braces

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/PayFineControl.java
> +  //File ready for Static review
D30 - line 24 PayFineControl.java - Change UIState -> UiState

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/PayFineControl.java
> +  //File ready for Static review
D31 - line 40 PayFineControl.java - remove method call from argument list of display
e.g.

ui.display(member.toString());

Replace with:

String memberInfo = member.toString();
	   ui.display(memberInfo);

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/PayFineControl.java
> +  //File ready for Static review
D32 - line 46 PayFineControl.java - Change method cancel -> cancelPayingFine

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/PayFineControl.java
> +  //File ready for Static review
D33 - line 47 PayFineControl.java - Change UIState -> UiState

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/PayFineControl.java
> +  //File ready for Static review
D34 - line 59 PayFineControl.java - Change method display -> displayMessage

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/PayFineControl.java
> +  //File ready for Static review
D35 - line 61 PayFineControl.java - remove method call from argument list of display
e.g.

ui.display(member.toString());

Replace with:

String memberInfo = member.toString();
	   ui.display(memberInfo);

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/PayFineControl.java
> +  //File ready for Static review
D36 - line 61 PayFineControl.java - Change method display -> displayMessage
e.g.

String memberInfo = member.toString();
ui.displayMessage(memberInfo);

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/PayFineControl.java
> +  //File ready for Static review
D37 - line 62 PayFineControl.java - Change UIState -> UiState

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/PayFineUI.java
>  	public static enum UIState { INITIALISED, READY, PAYING, COMPLETED, CANCELLED };
D38 - line 6 PayFineUI.java - Change UIState -> UiState

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/PayFineUI.java
>  	public static enum UIState { INITIALISED, READY, PAYING, COMPLETED, CANCELLED };
D39 - line 10 PayFineUI.java - Change UIState -> UiState

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/PayFineUI.java
>  	public static enum UIState { INITIALISED, READY, PAYING, COMPLETED, CANCELLED };
D40 - line 16 PayFineUI.java - Change UIState -> UiState

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/PayFineUI.java
>  	public static enum UIState { INITIALISED, READY, PAYING, COMPLETED, CANCELLED };
D41 - line 21 PayFineUI.java - Change UIState -> UiState

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/PayFineUI.java
>  	public static enum UIState { INITIALISED, READY, PAYING, COMPLETED, CANCELLED };
D42 - line 26 PayFineUI.java - Change method run -> runPayFine

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/PayFineUI.java
>  	public static enum UIState { INITIALISED, READY, PAYING, COMPLETED, CANCELLED };
D43 - line 27 PayFineUI.java - Change method output -> displayOutputMessage

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/PayFineUI.java
>  	public static enum UIState { INITIALISED, READY, PAYING, COMPLETED, CANCELLED };
D44 - line 34 PayFineUI.java - Change method input -> displayInputMessage

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/PayFineUI.java
>  	public static enum UIState { INITIALISED, READY, PAYING, COMPLETED, CANCELLED };
D45 - line 43 PayFineUI.java - Change e -> exception

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/PayFineUI.java
>  	public static enum UIState { INITIALISED, READY, PAYING, COMPLETED, CANCELLED };
D46 - line 44 PayFineUI.java - Change method output -> displayOutputMessage

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/PayFineUI.java
>  	public static enum UIState { INITIALISED, READY, PAYING, COMPLETED, CANCELLED };
D47 - line 50 PayFineUI.java - Change method input -> displayInputMessage

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/PayFineUI.java
>  	public static enum UIState { INITIALISED, READY, PAYING, COMPLETED, CANCELLED };
D48 - line 58 PayFineUI.java - Change e -> exception

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/PayFineUI.java
>  	public static enum UIState { INITIALISED, READY, PAYING, COMPLETED, CANCELLED };
D49 - line 44 PayFineUI.java - Change method output -> displayOutputMessage

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/PayFineUI.java
>  	public static enum UIState { INITIALISED, READY, PAYING, COMPLETED, CANCELLED };
D50 - line 67 PayFineUI.java - Change method output -> displayOutputMessage

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/PayFineUI.java
>  	public static enum UIState { INITIALISED, READY, PAYING, COMPLETED, CANCELLED };
D51 - line 71 PayFineUI.java - Change method output -> displayOutputMessage

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/PayFineUI.java
>  	public static enum UIState { INITIALISED, READY, PAYING, COMPLETED, CANCELLED };
D52 - line 75 PayFineUI.java - Change method output -> displayOutputMessage

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/PayFineUI.java
>  	public static enum UIState { INITIALISED, READY, PAYING, COMPLETED, CANCELLED };
D53 - line 83 PayFineUI.java - Change method input -> displayInputMessage

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/PayFineUI.java
>  	public static enum UIState { INITIALISED, READY, PAYING, COMPLETED, CANCELLED };
D54 - line 89 PayFineUI.java - Change method output -> displayOutputMessage

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/PayFineUI.java
>  	public static enum UIState { INITIALISED, READY, PAYING, COMPLETED, CANCELLED };
D55 - line 94 PayFineUI.java - Change method display -> displayMessage

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/PayFineUI.java
>  	public static enum UIState { INITIALISED, READY, PAYING, COMPLETED, CANCELLED };
D56 - line 95 PayFineUI.java - Change method output -> displayOutputMessage

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/FixBookUI.java
>  	public static enum UIState { INITIALISED, READY, FIXING, COMPLETED };
D57 - whole FixBookUI.java file - Change tabs -> 4 spaces

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/Loan.java
D58 - whole Loan.java file - Change tabs -> 4 spaces

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/PayFineControl.java
> +  //File ready for Static review
D59 - whole PayFineControl.java file - Change tabs -> 4 spaces

2018-08-15 13:20 UTC, bcurby commented on ITC205_BaseLine_Code/src/PayFineUI.java
>  	public static enum UIState { INITIALISED, READY, PAYING, COMPLETED, CANCELLED };
D60 - whole PayFineUI.java file - Change tabs -> 4 spaces

2018-08-15 22:15 UTC, bcurby commented on ITC205_BaseLine_Code/src/Loan.java
D62 - line 58 Loan.java - Change book.title -> book.getTitle 

Method 'title' is in Book.java on line 44

2018-08-15 22:28 UTC, bcurby commented on ITC205_BaseLine_Code/src/FixBookControl.java
> +  //File ready for Static review
D63 - line 12 FixBookControl.java - Add extra line of whitespace above public FixBookControl() so there are 2 lines of whitespace between it and previous block of code

2018-08-15 22:31 UTC, bcurby commented on ITC205_BaseLine_Code/src/FixBookControl.java
> +  //File ready for Static review
D64 - line 4-6 FixBookControl.java - Change private enum class to:

    private enum ControlState { INITIALISED, READY, FIXING };

2018-08-15 22:56 UTC, bcurby commented on ITC205_BaseLine_Code/src/FixBookControl.java
> +  //File ready for Static review
D65 - line 21, 31, 52 & 65 FixBookControl.java - Apply line wrapping so lines don't exceed 100 character limit e.g.

            throw new RuntimeException("FixBookControl:"
                + " cannot call bookScanned except in READY state");

2018-08-15 23:01 UTC, bcurby commented on ITC205_BaseLine_Code/src/FixBookUI.java
>  	public static enum UIState { INITIALISED, READY, FIXING, COMPLETED };
D66 - line 6 - 8 FixBookUI.java - Change private enum class to:

    public static enum UiState { INITIALISED, READY, FIXING, COMPLETED };

Also only one line of whitespace between enum and variables below

2018-08-15 23:02 UTC, bcurby commented on ITC205_BaseLine_Code/src/FixBookUI.java
>  	public static enum UIState { INITIALISED, READY, FIXING, COMPLETED };
D67 - line 15 FixBookUI.java - Add line of whitespace above method declaration so there is the required 2 lines of space

2018-08-15 23:07 UTC, bcurby commented on ITC205_BaseLine_Code/src/Loan.java
D68 - line 9-11 Loan.java - Change enum class to:

    public static enum LoanState { CURRENT, OVER_DUE, DISCHARGED };

Also only one line of whitespace between enum and variables below

2018-08-15 23:08 UTC, bcurby commented on ITC205_BaseLine_Code/src/Loan.java
D68 - line 20 Loan.java - Add line of whitespace above method declaration so there are 2 lines of whitespace

2018-08-15 23:13 UTC, bcurby commented on ITC205_BaseLine_Code/src/PayFineControl.java
> +  //File ready for Static review
D70 - line 4-6 PayFineControl.java - Change enum class to:

    private enum ControlState { INITIALISED, READY, PAYING, COMPLETED, CANCELLED };

Also only one line of whitespace between enum and variables below

2018-08-15 23:14 UTC, bcurby commented on ITC205_BaseLine_Code/src/PayFineControl.java
> +  //File ready for Static review
D71 - line 13 PayFineControl.java - Add line of whitespace above method declaration so there are 2 lines of whitespace

2018-08-15 23:21 UTC, bcurby commented on ITC205_BaseLine_Code/src/PayFineControl.java
> +  //File ready for Static review
D72 - line 21, 31 & 54 PayFineControl.java - Apply line wrapping so lines don't exceed limit of 100 characters e.g.

            throw new RuntimeException("PayFineControl:"
                + " cannot call payFine except in PAYING state");

Double check indent for new line is 4 spaces

2018-08-15 23:24 UTC, bcurby commented on ITC205_BaseLine_Code/src/PayFineUI.java
>  	public static enum UIState { INITIALISED, READY, PAYING, COMPLETED, CANCELLED };
D73 - line 6-8 PayFineUI.java file - Change enum class to:

    public static enum UiState { INITIALISED, READY, PAYING, COMPLETED, CANCELLED };

Also only one line of whitespace between enum and variables below

2018-08-15 23:25 UTC, bcurby commented on ITC205_BaseLine_Code/src/PayFineUI.java
>  	public static enum UIState { INITIALISED, READY, PAYING, COMPLETED, CANCELLED };
D74 - line 15 PayFineUI.java - Add line of whitespace above method declaration so there are 2 lines of whitespace

2018-08-15 23:27 UTC, bcurby commented on ITC205_BaseLine_Code/src/PayFineUI.java
>  	public static enum UIState { INITIALISED, READY, PAYING, COMPLETED, CANCELLED };
D75 - line 78 PayFineUI.java - Remove line of whitespace between code and closing braces

2018-08-15 23:54 UTC, bcurby commented
Please also fix D62 - 75

2018-08-16 02:15 UTC, bcurby commented on ITC205_BaseLine_Code/src/Loan.java
D76 - line 56-59 Loan.java - Apply line-wrapping so these lines don't exceed the 100 character limit. Also apply 4 space indentation e.g.
Before:
<img width="878" alt="before" src="https://user-images.githubusercontent.com/41361395/44183312-d1403580-a14d-11e8-8170-c3facaf189ae.png">

After:
<img width="711" alt="after" src="https://user-images.githubusercontent.com/41361395/44183338-f2088b00-a14d-11e8-9b49-994556c7e0b7.png">

2018-08-16 02:25 UTC, bcurby commented
Please also fix D76

2018-08-16 03:27 UTC, bcurby commented
All defects (D1 - D76) checked and requested changes confirmed.
Changes will now be approved.
Ready for Facilitator check and merge.

2018-08-16 03:27 UTC, bcurby approved these changes

2018-08-16 11:14 UTC, lukexjohnson commented
LUKEJ "mediator/facilitator": I have reviewed the code. Defects have been completed and align correctly, program runs well in IDE. Happy to proceed with merge.

2018-08-16 11:17 UTC, merged